[alias]
format       = "fmt"
format-check = "fmt --check"
lint         = "clippy --all-targets --all-features --examples --tests -- -D warnings"
test-cover   = "llvm-cov --all-features --lcov --output-path lcov.info"
